import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import baleia from '../../public/images/C-Baleia.png'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Oceânia",
  description: "Generated by create next app",
  icons: {
    icon: '/C-Baleia.png'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
