import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Oceânia",
  description: "Generated by create next app",
  icons: {
    icon: '/C-Baleia.png'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <div className="page-container">
          <main className="content-wrap">{children}</main>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
